const TOKEN_PLACEHOLDER = 'YOUR_MAPBOX_ACCESS_TOKEN';

export const MAPBOX_ACCESS_TOKEN =
  process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN ?? TOKEN_PLACEHOLDER;

export const MAPBOX_ACCESS_TOKEN_PLACEHOLDER = TOKEN_PLACEHOLDER;
